id: opecha:P000326
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17577
  title: གུར་མགོན་ཁྲོ་བཅུའི་གཏོར་བཟློག་དང་འབྲེལ་བའི་དྲག་པོའི་སྦྱིན་བསྲེགས།
  volume:
    1ae1981386794f2b818b0a083c291bfc:
      image_group_id: I1KG17938
      title: Volume 1 of gur mgon khro bcu'i gtor bzlog dang 'brel ba'i drag po'i
        sbyin bsregs/
      volume_number: 1
      total_pages: 68
  author: ''
ebook_metadata:
  title: གུར་མགོན་ཁྲོ་བཅུའི་གཏོར་བཟློག་དང་འབྲེལ་བའི་དྲག་པོའི་སྦྱིན་བསྲེགས།
  author: ''
  sku: P000326
  cover: cover.jpg
  layers:
  - pagination
