id: P000326
initial_creation_type: ocr
created_at: 12/03/2020
last_modified_at: 2021-12-16 15:34:09.444170
source_metadata:
  id: bdr:W1KG17577
  title: གུར་མགོན་ཁྲོ་བཅུའི་གཏོར་བཟློག་དང་འབྲེལ་བའི་དྲག་པོའི་སྦྱིན་བསྲེགས།
  author: ''
  volumes:
    1ae1981386794f2b818b0a083c291bfc:
      image_group_id: I1KG17938
      title: Volume 1 of gur mgon khro bcu'i gtor bzlog dang 'brel ba'i drag po'i
        sbyin bsregs/
      volume_number: 1
      total_pages: 68
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
